src/main/java/com/virtualpairprogrammers/domain/MenuCategory.java
package com.virtualpairprogrammers.domain;

public enum MenuCategory {
	STARTER, MAIN_COURSE, DESERT, DRINK
}

src/main/java/com/virtualpairprogrammers/domain/MenuItem.java
package com.virtualpairprogrammers.domain;

public class MenuItem {
	private int id;
	private String name;
	private String description;
	private MenuCategory category;
	private double price;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public MenuCategory getCategory() {
		return category;
	}
	public void setCategory(MenuCategory category) {
		this.category = category;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	
	public MenuItem(int id, String name, String description, MenuCategory category, double price) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.category = category;
		this.price = price;
	}
	
	public MenuItem() {}
	
	public String toString() {
		return (this.name + " (" + this.price + ")");
	}
	
	
}

src/main/java/com/virtualpairprogrammers/domain/Order.java
package com.virtualpairprogrammers.domain;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class Order {

	private Long id;
	private Map<MenuItem,Integer> currentOrder = new HashMap<MenuItem,Integer>();
	private String status;
	private String customer;

	public void addToOrder(MenuItem menuItem, int quantity) {
		int currentQuantity = 0;
		if (currentOrder.get(menuItem) != null) currentQuantity = currentOrder.get(menuItem);
		currentOrder.put(menuItem, currentQuantity + quantity);
	}

	public Double getOrderTotal() {
		double d = 0d;
		for (MenuItem menuItem : currentOrder.keySet()) {
			d += currentOrder.get(menuItem) * menuItem.getPrice();
		}
		return d;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		for (MenuItem menuItem : currentOrder.keySet()) {
			sb.append(
				menuItem.getName()
			).append(
				" : "
			).append(
				currentOrder.get(menuItem)
			).append(
				"<br/>"
			);
		}
		return sb.toString();
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}
	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		Order order = (Order) o;
		return Objects.equals(id, order.id);
	}

	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public void setCustomer(String customer) {
		this.customer = customer;
	}
	public String getCustomer() {
		return customer;
	}
	public void setContents(Map<MenuItem, Integer> contents) {
		this.currentOrder=contents;
	}

}

src/main/java/com/virtualpairprogrammers/web/servlets/KitchenAsyncServlet.java
package com.virtualpairprogrammers.web.servlets;

import javax.servlet.AsyncContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet(value = "/kitchenAsyncServlet", asyncSupported = true)
public class KitchenAsyncServlet extends HttpServlet {

   @Override
   protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
      AsyncContext asyncContext = req.startAsync(req, resp);   // Tomcat is assigning another http worker thread instead of using a different threadpool.. So actually.. this is pointless
      KitchenAsyncRunnableTask task = new KitchenAsyncRunnableTask();
      task.setAsyncContext(asyncContext);

      asyncContext.start(task);

   }
}

src/main/java/com/virtualpairprogrammers/web/servlets/MenuSearchServlet.java
package com.virtualpairprogrammers.web.servlets;

import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.data.MenuDaoFactory;
import com.virtualpairprogrammers.domain.MenuItem;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet("/searchResults.html")
public class MenuSearchServlet extends HttpServlet {

	@Override
	public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		String searchTerm = request.getParameter("searchTerm");
		
		MenuDao menuDao = MenuDaoFactory.getMenuDao();
		List<MenuItem> menuItems = menuDao.find(searchTerm);
		request.setAttribute("menuItems", menuItems);

		ServletContext servletContext = getServletContext();
		RequestDispatcher requestDispatcher = servletContext.getRequestDispatcher("/searchResults.jsp");
		requestDispatcher.forward(request, response);
	}
}

src/main/java/com/virtualpairprogrammers/web/servlets/OrderReceivedServlet.java
package com.virtualpairprogrammers.web.servlets;

import java.io.IOException;
import java.util.logging.Logger;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.virtualpairprogrammers.data.MenuDaoFactory;
import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.domain.Order;
import com.virtualpairprogrammers.web.websockets.KitchenDisplaySessionHandler;
import com.virtualpairprogrammers.web.websockets.KitchenDisplaySessionHandlerFactory;

@WebServlet("/orderReceived.html")
public class OrderReceivedServlet extends HttpServlet {
	static final Logger logger = Logger.getLogger("com.virtualpairprogrammers");
	final MenuDao menuDao = MenuDaoFactory.getMenuDao();

	@Override
	public void doPost (HttpServletRequest request, HttpServletResponse response) throws IOException {
		
		int maxId = menuDao.getFullMenu().size();
		Order order = menuDao.newOrder(request.getUserPrincipal().getName());
		for (int i = 0; i <maxId+1; i++) {
			String quantity = request.getParameter("item_" + i);
			 try {
			    int q = Integer.parseInt(quantity);
			    if (q > 0) {
			    	menuDao.addToOrder(order.getId(), menuDao.getItemByItemId(i), q);
			    	order.addToOrder(menuDao.getItemByItemId(i), q);
			    }
			  }  
			  catch(NumberFormatException nfe) {
			    //that's fine it just means there wasn't an order for this item 
			  }
		}
		logger.info("A new order has been received!");

		KitchenDisplaySessionHandler sessionHandler = KitchenDisplaySessionHandlerFactory.getHandler();
		sessionHandler.newOrder(order);

		HttpSession session = request.getSession();
		session.setAttribute("orderId", order.getId());
		
		String redirectUrl = "/thankYou.html";
		redirectUrl = response.encodeURL(redirectUrl);
		response.sendRedirect(redirectUrl);

	}
}

src/main/java/com/virtualpairprogrammers/web/servlets/OrderServlet.java
package com.virtualpairprogrammers.web.servlets;

import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.data.MenuDaoFactory;
import com.virtualpairprogrammers.domain.MenuItem;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.HttpConstraint;
import javax.servlet.annotation.ServletSecurity;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet("/order.html")
@ServletSecurity(
	@HttpConstraint(rolesAllowed = {"user"})
)
public class OrderServlet extends HttpServlet {

	@Override
	public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		MenuDao menuDao = MenuDaoFactory.getMenuDao();
		List<MenuItem> menuItems = menuDao.getFullMenu();

		request.setAttribute("menuItems", menuItems);
		ServletContext servletContext = getServletContext();
		RequestDispatcher requestDispatcher = servletContext.getRequestDispatcher("/order.jsp");
		requestDispatcher.forward(request, response);
	}
}

src/main/java/com/virtualpairprogrammers/web/servlets/OrderStatusAjaxServlet.java
package com.virtualpairprogrammers.web.servlets;

import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.data.MenuDaoFactory;
import org.json.JSONObject;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

@WebServlet("/updatedStatus")
public class OrderStatusAjaxServlet extends HttpServlet {

   @Override
   protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
      Long orderId = Long.valueOf(req.getParameter("orderId"));
      MenuDao menuDao = MenuDaoFactory.getMenuDao();
      String orderStatus = menuDao.getOrderById(orderId).getStatus();

      PrintWriter out = resp.getWriter();
      resp.setContentType("text/html");

      JSONObject json = new JSONObject();
      json.put("orderStatus", orderStatus);
      SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
      json.put("time", sdf.format(new Date()));

      out.write(json.toString());

      out.close();
   }
}

src/main/java/com/virtualpairprogrammers/web/servlets/ProcessOrderServlet.java
package com.virtualpairprogrammers.web.servlets;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.data.MenuDaoFactory;
import com.virtualpairprogrammers.domain.Order;
import com.virtualpairprogrammers.web.websockets.KitchenDisplaySessionHandler;
import com.virtualpairprogrammers.web.websockets.KitchenDisplaySessionHandlerFactory;

@WebServlet("/processorder.html")
public class ProcessOrderServlet extends HttpServlet{
	static final Logger logger = Logger.getLogger("com.virtualpairprogrammers.web");

	@Override
	public void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		MenuDao menuDao = MenuDaoFactory.getMenuDao();
		List<Order> orders;
		orders = menuDao.getAllOrders();
		request.setAttribute("orders", orders);

		List<String> statuses = new ArrayList<>();
		statuses.add("order accepted");
		statuses.add("payment received");
		statuses.add("being prepared");
		statuses.add("ready for collection");

		request.setAttribute("statuses", statuses);

		ServletContext context = getServletContext();
		RequestDispatcher dispatch = context.getRequestDispatcher("/processorder.jsp");
		dispatch.forward(request,response);
	}

	@Override
	public void doPost (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		MenuDao menuDao = MenuDaoFactory.getMenuDao();
		Long id = Long.valueOf(request.getParameter("id")); //NumberFormatException
		String status =  request.getParameter("status");
		logger.log(Level.INFO, "{0} : {1} ", new Object[]{id, status});
		menuDao.updateOrderStatus(id,status);

		Order order = menuDao.getOrderById(id);
		KitchenDisplaySessionHandler kDSHandler = KitchenDisplaySessionHandlerFactory.getHandler();
		kDSHandler.amendOrder(order);

		doGet(request,response);
	}
}

src/main/java/com/virtualpairprogrammers/web/servlets/ThankYouServlet.java
package com.virtualpairprogrammers.web.servlets;

import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.data.MenuDaoFactory;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.HttpConstraint;
import javax.servlet.annotation.ServletSecurity;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@WebServlet("/thankYou.html")
@ServletSecurity(
	@HttpConstraint(rolesAllowed = {"user"})
)
public class ThankYouServlet extends HttpServlet {
	@Override
	public void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();
		Long orderId = (Long) session.getAttribute("orderId");

		MenuDao menuDao = MenuDaoFactory.getMenuDao();
		Double total = menuDao.getOrderTotal(orderId);
		String orderStatus = menuDao.getOrderById(orderId).getStatus();

		if (total == null) {
			response.sendRedirect("/order.html");
			return;
		}

		request.setAttribute("orderId", orderId);
		request.setAttribute("total", total);
		request.setAttribute("currency", "USD");
		request.setAttribute("orderStatus", orderStatus);

		ServletContext servletContext = getServletContext();
		RequestDispatcher requestDispatcher = servletContext.getRequestDispatcher("/thankYou.jsp");
		requestDispatcher.forward(request, response);
	}
}

src/main/java/com/virtualpairprogrammers/web/servlets/ViewMenuServlet.java
package com.virtualpairprogrammers.web.servlets;

import com.virtualpairprogrammers.data.MenuDao;
import com.virtualpairprogrammers.data.MenuDaoFactory;
import com.virtualpairprogrammers.domain.MenuItem;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet("")
public class ViewMenuServlet extends HttpServlet {

	@Override
	public void service(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		
		MenuDao menuDao = MenuDaoFactory.getMenuDao();
		List<MenuItem> menuItems = menuDao.getFullMenu();

		request.setAttribute("menuItems", menuItems);
		ServletContext servletContext = getServletContext();
		RequestDispatcher requestDispatcher = servletContext.getRequestDispatcher("/viewMenu.jsp");
		requestDispatcher.forward(request, response);

	}
	
}

src/main/webapp/footer.jsp
</div>                                                              <!-- closes <div class="main"> from header.jsp -->
<div class="links">
    <a href='about.html' class="link">About Ricky's</a>
    <a href='tc.html' class="link">Terms and Conditions</a>
    <a href='privacy.html' class="link">Privacy Policy</a>
    <a href='contact.html' class="link">Contact Us</a>
    <div class="clearBoth"></div>
</div>

src/main/webapp/header.jsp
<head>
	<link rel="stylesheet" type="text/css" href="styles.css" />
</head>
<div class="logo">
	<h1>Ricky's Restaurant</h1>
</div>
<div class="links">
    <a href='/' class="button">View the menu</a>
    <a href='searchResults.html?searchTerm=chicken' class="button">View all chicken dishes</a>
    <a href='search.html' class="button">Search the menu</a>
    <a href='order.html' class="button">Order a meal to collect</a>
    <div class="clearBoth"></div>
</div>
<div class="main">

src/main/webapp/helloworld.jsp
<html>
<body>
    <h1>Hello World</h1>
</body>
</html>

src/main/webapp/kitchendisplay.jsp
<html>
	<head>
		<script>
            var connectionOpen = false;
            var nextOrder = 1;
            function getOrders(){
                if(!connectionOpen){
                	connectionOpen = true;
                    var xmlhttp = new XMLHttpRequest();
                    xmlhttp.onreadystatechange = function() {
                        if (xmlhttp.readyState==4 && xmlhttp.status==200) {
                        	connectionOpen = false;
                        	nextOrder++;
                            var ordersDiv = document.getElementById("orders");
                            ordersDiv.innerHTML = xmlhttp.responseText + ordersDiv.innerHTML;
                        }
                    }
                    xmlhttp.open("GET", "kitchenAsyncServlet?size=" + nextOrder, true);
                    xmlhttp.send();
                }
            }
            setInterval(getOrders, 500);
        </script>
</head>


<body>
	<h1>Ricky's Restaurant - Live orders</h1>

	<div id="orders"></div>


</body>
</html>

src/main/webapp/order.jsp
<%@ page import = "com.virtualpairprogrammers.domain.MenuItem"      %>
<%@ page import = "java.util.List"                                  %>

<html>
<body>
    <jsp:include page="/header.jsp" />

    <h2>Order</h2>

    <form action="orderReceived.html" method="POST">
        <ul>
            <%
            List<MenuItem> menuItems = (List<MenuItem>) request.getAttribute("menuItems");
            for (MenuItem menuItem : menuItems)
                out.println("<li>" + menuItem + "<input type='text' name='item_" +menuItem.getId()+ "'/></li>");
            %>
		</ul>
	    <input type="submit" />
	</form>

    <jsp:include page="/footer.jsp" />
</body>
</html>

src/main/webapp/processorder.jsp
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>

<html>
<body>
	<jsp:include page="/header.jsp" />
	<h2>Update Orders</h2>
	
	<table style="border: 1px solid;">
		<tr><th>Order ID</th><th>Price</th><th>Status</th></tr>
		<c:forEach items="${orders}" var="order" > 
			<tr>
				<td>${order.id}</td>
				<td> $ ${order.orderTotal}</td>
				<td>
					<form action='processorder.html' method='POST' >
						<input type="hidden" name="id" value="${order.id}" />
						<select name="status">
							<option value="${order.status}" selected>${order.status}</option>
							<c:forEach items="${statuses}" var="item">
								<c:if test="${!item.equals(order.status)}">
									<option value="${item}">${item}</option> 
								</c:if>
							</c:forEach>
						</select>
						<input type="submit" value="Update"/>
					</form>
				</td>
			</tr>
		</c:forEach>
	</table>

</body>
</html>

src/main/webapp/searchResults.jsp
<%@ page import = "com.virtualpairprogrammers.domain.MenuItem"      %>
<%@ page import = "java.util.List"                                  %>

<html>
<body>
    <jsp:include page="/header.jsp" />

    <h2>Your search results: </h2>
    <ul>
        <%  List<MenuItem> menuItems = (List<MenuItem>) request.getAttribute("menuItems");  %>
        <%  for (MenuItem menuItem : menuItems) {                                           %>
            <li>
        <%=         menuItem                                                                %>
            </li>
        <%  }                                                                               %>
    </ul>

    <jsp:include page="footer.jsp" />
</body>
</html>

src/main/webapp/squares.jsp
<html>
<head>
<title>First 10 Squares</title>
</head>
<body>
<h1>The First 10 Squares:</h1>

<%  for(int i=1; i<=10; i++) out.println (i*i);    %>

</body>
</html>

src/main/webapp/thankYou.jsp
<%@ taglib  prefix="c"      uri="http://java.sun.com/jsp/jstl/core"     %>
<%@ taglib  prefix="fmt"    uri="http://java.sun.com/jsp/jstl/fmt"      %>

<html>
<head>
    <script>
        function updateOrderStatus() {
            var request = new XMLHttpRequest();
            request.onreadystatechange = function() {
                if (this.readyState == 4) {
                    var json = JSON.parse(this.responseText);
                    document.getElementById("orderStatus").innerHTML = json.orderStatus;
                    document.getElementById("time").innerHTML = "Last updated: " + json.time;
                }
            }
            request.open("GET", "/updatedStatus?orderId=${orderId}", true);
            request.send();
        }
        
        window.setInterval(
            function() {
                updateOrderStatus();
            }, 
            2000
        );
    </script>
</head>
    <body>
        <jsp:include page="/header.jsp" />
        <h2>Thank you for your patronage</h2>

        <p>Order received, thank you! Grand total:
        <fmt:formatNumber value="${total}" type="currency" currencyCode="${currency}" /></p>

        <p>
            The current status of your order is: [ <span id="orderStatus">${orderStatus}</span> ]
            <input type="button" value="Check Status" onclick="updateOrderStatus()"/>
        </p>
        <p id="time"></p>

        <jsp:include page="/footer.jsp"/>
    </body>
</html>

src/main/webapp/viewMenu.jsp
<%@ taglib  uri="http://java.sun.com/jsp/jstl/core"     prefix="c"   %>

<html>
<body>
    <jsp:include page="/header.jsp" />

    <h2>Menu</h2>
    <ul>
        <c:forEach items="${menuItems}" var="menuItem">
            <c:if test="${menuItem.price <= 10}">
                <li>${menuItem} - ${menuItem.description}</li>
            </c:if>
        </c:forEach>
    </ul>

    <jsp:include page="/footer.jsp" />
</body>
</html>